version: "3"

services:

  proxy:
    build: ./services/proxy
    ports:
      - 80:80
    restart: always
    
  website:
    image: node:14
    env_file:
      - ./environment/website.development.env
    environment:
      - PORT=3000
    working_dir: /app/services/website
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    command: ./entrypoint.sh